stages:
  - check
  - test
  - build
  - release

default:
  image: python:3.9

check:
  stage: check
  image: python:3.6
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

.test:
  stage: test
  before_script:
    - pip install .[dev]
  script:
    - pytest -v --junitxml=report.xml --cov=gidgetlab tests
  artifacts:
    when: always
    reports:
      junit: report.xml

test-python36:
  extends: .test
  image: python:3.6

test-python37:
  extends: .test
  image: python:3.7

test-python38:
  extends: .test
  image: python:3.8

test-python39:
  extends: .test
  image: python:3.9

build-pypi-package:
  stage: build
  script:
    - python setup.py check sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

release-pypi:
  stage: release
  variables:
    GIT_STRATEGY: none
  before_script:
    - pip install twine
  script:
    - twine upload dist/*
  only:
    - tags
