stages:
  - check
  - test

check:
  stage: check
  image: python:3.6
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

test-python36:
  stage: test
  image: python:3.6
  before_script:
    - pip install .[dev]
  script:
    - pytest --cov=gidgetlab

test-python37:
  stage: test
  image: python:3.7
  before_script:
    - pip install .[dev]
  script:
    - pytest --cov=gidgetlab
