stages:
  - check
  - test
  - release

check:
  stage: check
  image: python:3.6
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

test-python36:
  stage: test
  image: python:3.6
  before_script:
    - pip install .[dev]
  script:
    - pytest --cov=gidgetlab

test-python37:
  stage: test
  image: python:3.7
  before_script:
    - pip install .[dev]
  script:
    - pytest --cov=gidgetlab

release-pypi:
  stage: release
  image: python:3.7
  before_script:
    - pip install twine
  script:
    - python setup.py check sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
