repos:
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        additional_dependencies:
          - 'tornado'
          - types-cachetools
          - types-setuptools
        args: [--ignore-missing-imports, --strict]
        exclude: (tests/|docs/)
