language: python
cache: pip
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
    python: "nightly"

before_install:
  - pip install -U ".[dev]"
  - pip install -U pytest-cov sphinx mypy
script:
  - pytest --cov=gidgethub
  - mypy --ignore-missing-imports --strict gidgethub/*.py
  - sphinx-build -nW -q -b html -b linkcheck -d docs/_build/doctrees docs docs/_build/html
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
